In [1]:
import numpy as np

In [2]:
def sigmoid(z):
    return np.array([ 1 / (1 + np.exp(x)) for x in z])

def sigmoid_derivative(z):
    return np.array([x * (1-x) for x in z])

def relu(x):
    return np.max(x, 0)

def relu_derivative(x):
    x[x<=0] = 0
    x[x>0] = 1
    return x

In [3]:
X = np.array([[0, 1, 1], [0, 1, 1], [1, 0, 0]])
y = np.array([[0, 0], [0,1], [1, 0]])
X.shape

(3, 3)

In [4]:
y.shape

(3, 2)

In [5]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], 2)
        self.y = y
        self.output = np.zeros_like(y)
        
    def feedforward(self):
        self.output = sigmoid(np.dot(self.input, self.weights1))
        
    def backprop(self):
        d_weights1 = np.dot(self.input.T, ((self.y - self.output)* sigmoid_derivative(self.output)))
        self.weights1 += d_weights1
        
    def train(self):
        self.feedforward()
        self.backprop()
        

    
    def loss(self, y):
        return np.mean((y - self.output) **2) #MSE, RMSE, MAE
        

In [6]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], 16)
        self.weights2 = np.random.rand(16, 8)
        self.weights3 = np.random.rand(8, 2)
        self.y = y
        self.output = np.zeros_like(y)
        
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        self.output = sigmoid(np.dot(self.layer2, self.weights3))
        
    def backprop(self):
        d_weights3 = np.dot(self.layer2.T, (2 *( self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights2 = np.dot(self.layer1.T, (np.dot(2 * (self.y - self.output) * 
                                                   sigmoid_derivative(self.output), 
                                                   self.weights3.T) * sigmoid_derivative(self.layer2)))
        d_weights1 = np.dot(self.input.T, (np.dot(np.dot(2*(self.y - self.output) * 
                                                         sigmoid_derivative(self.output), self.weights3.T) * 
                                                  sigmoid_derivative(self.layer2), self.weights2.T) * 
                                           sigmoid_derivative(self.layer1)))
        self.weights1 += d_weights1
        self.weights2 += d_weights2
        self.weights3 += d_weights3
        
    def train(self):
        self.feedforward()
        self.backprop()

In [7]:
model = NeuralNetwork(X, y)

In [8]:
model.output

array([[0, 0],
       [0, 0],
       [0, 0]])

In [9]:
model.train()

In [10]:
model.input

array([[0, 1, 1],
       [0, 1, 1],
       [1, 0, 0]])

In [11]:
model.output

array([[0.38752865, 0.4185225 ],
       [0.38752865, 0.4185225 ],
       [0.45202116, 0.46897186]])